[2021-10-29 07:31:20,837] {processor.py:163} INFO - Started process (PID=17156) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:31:20,850] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:31:20,851] {logging_mixin.py:109} INFO - [2021-10-29 07:31:20,851] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:31:20,945] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:31:20,947] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.114 seconds
[2021-10-29 07:31:51,506] {processor.py:163} INFO - Started process (PID=17180) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:31:51,508] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:31:51,509] {logging_mixin.py:109} INFO - [2021-10-29 07:31:51,509] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:31:51,531] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:31:51,537] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.035 seconds
[2021-10-29 07:32:22,172] {processor.py:163} INFO - Started process (PID=17204) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:32:22,175] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:32:22,176] {logging_mixin.py:109} INFO - [2021-10-29 07:32:22,175] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:32:22,199] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:32:22,208] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.039 seconds
[2021-10-29 07:32:52,543] {processor.py:163} INFO - Started process (PID=17235) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:32:52,555] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:32:52,557] {logging_mixin.py:109} INFO - [2021-10-29 07:32:52,557] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:32:52,588] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:32:52,601] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.061 seconds
[2021-10-29 07:33:22,855] {processor.py:163} INFO - Started process (PID=17262) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:33:22,857] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:33:22,858] {logging_mixin.py:109} INFO - [2021-10-29 07:33:22,858] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:33:22,874] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:33:22,883] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.031 seconds
[2021-10-29 07:33:53,847] {processor.py:163} INFO - Started process (PID=17286) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:33:53,849] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:33:53,850] {logging_mixin.py:109} INFO - [2021-10-29 07:33:53,850] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:33:53,879] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:33:53,891] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.047 seconds
[2021-10-29 07:34:24,410] {processor.py:163} INFO - Started process (PID=17310) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:34:24,412] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:34:24,412] {logging_mixin.py:109} INFO - [2021-10-29 07:34:24,412] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:34:24,454] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:34:24,457] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.049 seconds
[2021-10-29 07:34:54,903] {processor.py:163} INFO - Started process (PID=17341) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:34:54,966] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:34:54,967] {logging_mixin.py:109} INFO - [2021-10-29 07:34:54,967] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:34:55,234] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:34:55,317] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.417 seconds
[2021-10-29 07:35:25,594] {processor.py:163} INFO - Started process (PID=17358) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:35:25,620] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:35:25,621] {logging_mixin.py:109} INFO - [2021-10-29 07:35:25,621] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:35:25,674] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:35:25,697] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.106 seconds
[2021-10-29 07:35:55,933] {processor.py:163} INFO - Started process (PID=17382) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:35:56,025] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:35:56,067] {logging_mixin.py:109} INFO - [2021-10-29 07:35:56,067] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:35:56,375] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:35:56,476] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.565 seconds
[2021-10-29 07:36:27,314] {processor.py:163} INFO - Started process (PID=17406) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:36:27,317] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:36:27,318] {logging_mixin.py:109} INFO - [2021-10-29 07:36:27,318] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:36:27,335] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:36:27,338] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.027 seconds
[2021-10-29 07:36:57,709] {processor.py:163} INFO - Started process (PID=17429) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:36:57,711] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:36:57,712] {logging_mixin.py:109} INFO - [2021-10-29 07:36:57,712] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:36:57,731] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:36:57,734] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.028 seconds
[2021-10-29 07:37:27,820] {processor.py:163} INFO - Started process (PID=17453) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:37:27,827] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:37:27,828] {logging_mixin.py:109} INFO - [2021-10-29 07:37:27,827] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:37:27,847] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:37:27,850] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.036 seconds
[2021-10-29 07:37:58,164] {processor.py:163} INFO - Started process (PID=17471) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:37:58,166] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:37:58,167] {logging_mixin.py:109} INFO - [2021-10-29 07:37:58,167] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:37:58,247] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:37:58,250] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.127 seconds
[2021-10-29 07:38:28,853] {processor.py:163} INFO - Started process (PID=17491) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:38:29,085] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:38:29,087] {logging_mixin.py:109} INFO - [2021-10-29 07:38:29,087] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:38:30,475] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:38:30,537] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 1.690 seconds
[2021-10-29 07:39:00,870] {processor.py:163} INFO - Started process (PID=17515) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:39:00,898] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:39:00,919] {logging_mixin.py:109} INFO - [2021-10-29 07:39:00,919] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:39:01,203] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:39:01,252] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.436 seconds
[2021-10-29 07:39:31,483] {processor.py:163} INFO - Started process (PID=17529) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:39:31,495] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:39:31,496] {logging_mixin.py:109} INFO - [2021-10-29 07:39:31,496] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:39:31,601] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:39:31,611] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.143 seconds
[2021-10-29 07:40:02,334] {processor.py:163} INFO - Started process (PID=17553) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:40:02,343] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:40:02,409] {logging_mixin.py:109} INFO - [2021-10-29 07:40:02,409] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:40:02,749] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:40:02,752] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.422 seconds
[2021-10-29 07:40:33,119] {processor.py:163} INFO - Started process (PID=17567) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:40:33,124] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:40:33,125] {logging_mixin.py:109} INFO - [2021-10-29 07:40:33,125] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:40:33,147] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:40:33,155] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.043 seconds
[2021-10-29 07:41:03,863] {processor.py:163} INFO - Started process (PID=17592) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:41:03,905] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:41:03,920] {logging_mixin.py:109} INFO - [2021-10-29 07:41:03,919] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:41:03,986] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:41:03,994] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.134 seconds
[2021-10-29 07:41:34,620] {processor.py:163} INFO - Started process (PID=17606) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:41:34,639] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:41:34,647] {logging_mixin.py:109} INFO - [2021-10-29 07:41:34,647] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:41:34,727] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:41:34,755] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.138 seconds
[2021-10-29 07:41:38,452] {processor.py:163} INFO - Started process (PID=17618) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:41:38,464] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:41:38,465] {logging_mixin.py:109} INFO - [2021-10-29 07:41:38,465] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:41:38,634] {logging_mixin.py:109} INFO - [2021-10-29 07:41:38,599] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:41:38,728] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:41:38,792] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.344 seconds
[2021-10-29 07:42:09,419] {processor.py:163} INFO - Started process (PID=17631) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:42:09,441] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:42:09,442] {logging_mixin.py:109} INFO - [2021-10-29 07:42:09,442] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:42:09,542] {logging_mixin.py:109} INFO - [2021-10-29 07:42:09,458] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:42:09,689] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:42:09,761] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.466 seconds
[2021-10-29 07:42:31,451] {processor.py:163} INFO - Started process (PID=17645) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:42:31,453] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:42:31,454] {logging_mixin.py:109} INFO - [2021-10-29 07:42:31,454] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:42:31,468] {logging_mixin.py:109} INFO - [2021-10-29 07:42:31,467] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:42:31,507] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:42:31,524] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.081 seconds
[2021-10-29 07:43:01,673] {processor.py:163} INFO - Started process (PID=17669) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:43:01,679] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:43:01,692] {logging_mixin.py:109} INFO - [2021-10-29 07:43:01,692] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:43:01,740] {logging_mixin.py:109} INFO - [2021-10-29 07:43:01,739] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:43:01,780] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:43:01,794] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.124 seconds
[2021-10-29 07:43:31,900] {processor.py:163} INFO - Started process (PID=17693) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:43:31,904] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:43:31,905] {logging_mixin.py:109} INFO - [2021-10-29 07:43:31,905] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:43:31,913] {logging_mixin.py:109} INFO - [2021-10-29 07:43:31,912] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:43:31,931] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:43:31,939] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.048 seconds
[2021-10-29 07:44:02,372] {processor.py:163} INFO - Started process (PID=17717) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:44:02,385] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:44:02,389] {logging_mixin.py:109} INFO - [2021-10-29 07:44:02,388] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:44:02,409] {logging_mixin.py:109} INFO - [2021-10-29 07:44:02,408] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:44:02,433] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:44:02,441] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.072 seconds
[2021-10-29 07:44:32,646] {processor.py:163} INFO - Started process (PID=17748) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:44:32,647] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:44:32,648] {logging_mixin.py:109} INFO - [2021-10-29 07:44:32,648] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:44:32,667] {logging_mixin.py:109} INFO - [2021-10-29 07:44:32,666] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:44:33,047] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:44:33,163] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.520 seconds
[2021-10-29 07:45:03,685] {processor.py:163} INFO - Started process (PID=17765) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:45:03,689] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:45:03,696] {logging_mixin.py:109} INFO - [2021-10-29 07:45:03,696] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:45:03,736] {logging_mixin.py:109} INFO - [2021-10-29 07:45:03,723] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:45:03,783] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:45:03,802] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.126 seconds
[2021-10-29 07:45:34,352] {processor.py:163} INFO - Started process (PID=17789) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:45:34,356] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:45:34,357] {logging_mixin.py:109} INFO - [2021-10-29 07:45:34,357] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:45:34,364] {logging_mixin.py:109} INFO - [2021-10-29 07:45:34,363] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:45:34,377] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:45:34,385] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.036 seconds
[2021-10-29 07:46:05,014] {processor.py:163} INFO - Started process (PID=17813) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:46:05,017] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:46:05,018] {logging_mixin.py:109} INFO - [2021-10-29 07:46:05,018] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:46:05,027] {logging_mixin.py:109} INFO - [2021-10-29 07:46:05,026] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:46:05,042] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:46:05,050] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.039 seconds
[2021-10-29 07:46:36,394] {processor.py:163} INFO - Started process (PID=17837) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:46:36,397] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:46:36,397] {logging_mixin.py:109} INFO - [2021-10-29 07:46:36,397] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:46:36,592] {logging_mixin.py:109} INFO - [2021-10-29 07:46:36,591] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:46:36,725] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:46:36,810] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.546 seconds
[2021-10-29 07:47:07,347] {processor.py:163} INFO - Started process (PID=17851) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:47:07,352] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:47:07,354] {logging_mixin.py:109} INFO - [2021-10-29 07:47:07,354] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:47:07,365] {logging_mixin.py:109} INFO - [2021-10-29 07:47:07,364] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:47:07,386] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:47:07,397] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.055 seconds
[2021-10-29 07:47:37,990] {processor.py:163} INFO - Started process (PID=17875) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:47:38,019] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:47:38,020] {logging_mixin.py:109} INFO - [2021-10-29 07:47:38,020] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:47:38,027] {logging_mixin.py:109} INFO - [2021-10-29 07:47:38,026] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:47:38,271] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:47:38,336] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.473 seconds
[2021-10-29 07:48:09,157] {processor.py:163} INFO - Started process (PID=17888) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:48:09,160] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:48:09,161] {logging_mixin.py:109} INFO - [2021-10-29 07:48:09,161] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:48:09,169] {logging_mixin.py:109} INFO - [2021-10-29 07:48:09,168] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:48:09,188] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:48:09,205] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.051 seconds
[2021-10-29 07:48:39,462] {processor.py:163} INFO - Started process (PID=17912) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:48:39,472] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:48:39,472] {logging_mixin.py:109} INFO - [2021-10-29 07:48:39,472] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:48:39,505] {logging_mixin.py:109} INFO - [2021-10-29 07:48:39,504] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:48:39,593] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:48:39,615] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.157 seconds
[2021-10-29 07:49:01,468] {processor.py:163} INFO - Started process (PID=17934) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:49:01,625] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:49:01,625] {logging_mixin.py:109} INFO - [2021-10-29 07:49:01,625] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:49:01,660] {logging_mixin.py:109} INFO - [2021-10-29 07:49:01,659] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:49:01,848] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:49:01,888] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.424 seconds
[2021-10-29 07:49:08,025] {processor.py:163} INFO - Started process (PID=17936) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:49:08,056] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:49:08,057] {logging_mixin.py:109} INFO - [2021-10-29 07:49:08,057] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:49:08,145] {logging_mixin.py:109} INFO - [2021-10-29 07:49:08,144] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:49:08,341] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:49:08,428] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.406 seconds
[2021-10-29 07:49:38,780] {processor.py:163} INFO - Started process (PID=17960) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:49:38,783] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:49:38,784] {logging_mixin.py:109} INFO - [2021-10-29 07:49:38,784] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:49:38,820] {logging_mixin.py:109} INFO - [2021-10-29 07:49:38,819] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:49:38,951] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:49:38,992] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.216 seconds
[2021-10-29 07:50:09,147] {processor.py:163} INFO - Started process (PID=17974) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:50:09,238] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:50:09,247] {logging_mixin.py:109} INFO - [2021-10-29 07:50:09,247] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:50:09,254] {logging_mixin.py:109} INFO - [2021-10-29 07:50:09,254] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:50:09,359] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:50:09,416] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.273 seconds
[2021-10-29 07:50:27,839] {processor.py:163} INFO - Started process (PID=17997) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:50:27,843] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:50:27,844] {logging_mixin.py:109} INFO - [2021-10-29 07:50:27,844] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:50:27,894] {logging_mixin.py:109} INFO - [2021-10-29 07:50:27,894] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:50:27,984] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:50:28,003] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.230 seconds
[2021-10-29 07:50:58,106] {processor.py:163} INFO - Started process (PID=18012) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:50:58,123] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:50:58,126] {logging_mixin.py:109} INFO - [2021-10-29 07:50:58,126] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:50:58,136] {logging_mixin.py:109} INFO - [2021-10-29 07:50:58,135] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:50:58,175] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:50:58,187] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.085 seconds
[2021-10-29 07:51:28,670] {processor.py:163} INFO - Started process (PID=18035) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:51:28,672] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:51:28,673] {logging_mixin.py:109} INFO - [2021-10-29 07:51:28,673] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:51:28,720] {logging_mixin.py:109} INFO - [2021-10-29 07:51:28,719] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:51:28,807] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:51:28,827] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.193 seconds
[2021-10-29 07:51:59,756] {processor.py:163} INFO - Started process (PID=18059) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:51:59,760] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:51:59,761] {logging_mixin.py:109} INFO - [2021-10-29 07:51:59,761] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:51:59,771] {logging_mixin.py:109} INFO - [2021-10-29 07:51:59,771] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:51:59,861] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:51:59,871] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.154 seconds
[2021-10-29 07:52:30,273] {processor.py:163} INFO - Started process (PID=18082) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:52:30,438] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:52:30,438] {logging_mixin.py:109} INFO - [2021-10-29 07:52:30,438] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:52:30,561] {logging_mixin.py:109} INFO - [2021-10-29 07:52:30,560] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:52:31,179] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:52:31,309] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 1.039 seconds
[2021-10-29 07:53:02,308] {processor.py:163} INFO - Started process (PID=18106) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:53:02,329] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:53:02,330] {logging_mixin.py:109} INFO - [2021-10-29 07:53:02,330] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:53:02,452] {logging_mixin.py:109} INFO - [2021-10-29 07:53:02,451] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:53:02,595] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:53:02,639] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.334 seconds
[2021-10-29 07:53:33,381] {processor.py:163} INFO - Started process (PID=18120) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:53:33,383] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:53:33,384] {logging_mixin.py:109} INFO - [2021-10-29 07:53:33,384] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:53:33,488] {logging_mixin.py:109} INFO - [2021-10-29 07:53:33,487] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:53:33,924] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:53:34,002] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.714 seconds
[2021-10-29 07:54:04,518] {processor.py:163} INFO - Started process (PID=18144) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:54:04,550] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:54:04,562] {logging_mixin.py:109} INFO - [2021-10-29 07:54:04,562] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:54:04,657] {logging_mixin.py:109} INFO - [2021-10-29 07:54:04,584] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:54:04,694] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:54:04,713] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.198 seconds
[2021-10-29 07:54:34,949] {processor.py:163} INFO - Started process (PID=18168) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:54:34,964] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:54:34,972] {logging_mixin.py:109} INFO - [2021-10-29 07:54:34,972] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:54:35,161] {logging_mixin.py:109} INFO - [2021-10-29 07:54:35,160] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:54:35,311] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:54:35,340] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.455 seconds
[2021-10-29 07:55:05,916] {processor.py:163} INFO - Started process (PID=18202) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:55:05,956] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:55:05,959] {logging_mixin.py:109} INFO - [2021-10-29 07:55:05,959] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:55:06,047] {logging_mixin.py:109} INFO - [2021-10-29 07:55:06,047] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:55:06,102] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:55:06,170] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.258 seconds
[2021-10-29 07:55:36,751] {processor.py:163} INFO - Started process (PID=18226) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:55:36,776] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:55:36,777] {logging_mixin.py:109} INFO - [2021-10-29 07:55:36,777] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:55:36,786] {logging_mixin.py:109} INFO - [2021-10-29 07:55:36,786] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:55:36,898] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:55:36,936] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.193 seconds
[2021-10-29 07:56:07,667] {processor.py:163} INFO - Started process (PID=18250) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:56:07,702] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:56:07,703] {logging_mixin.py:109} INFO - [2021-10-29 07:56:07,703] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:56:07,767] {logging_mixin.py:109} INFO - [2021-10-29 07:56:07,710] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:56:07,842] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:56:07,862] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.199 seconds
[2021-10-29 07:56:37,974] {processor.py:163} INFO - Started process (PID=18275) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:56:37,977] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:56:37,978] {logging_mixin.py:109} INFO - [2021-10-29 07:56:37,978] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:56:38,071] {logging_mixin.py:109} INFO - [2021-10-29 07:56:38,026] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:56:38,136] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:56:38,264] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.329 seconds
[2021-10-29 07:57:08,574] {processor.py:163} INFO - Started process (PID=18289) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:57:08,587] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:57:08,587] {logging_mixin.py:109} INFO - [2021-10-29 07:57:08,587] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:57:08,594] {logging_mixin.py:109} INFO - [2021-10-29 07:57:08,594] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:57:08,672] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:57:08,701] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.130 seconds
[2021-10-29 07:57:39,010] {processor.py:163} INFO - Started process (PID=18313) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:57:39,016] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:57:39,017] {logging_mixin.py:109} INFO - [2021-10-29 07:57:39,017] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:57:39,025] {logging_mixin.py:109} INFO - [2021-10-29 07:57:39,025] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:57:39,039] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:57:39,047] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.041 seconds
[2021-10-29 07:58:09,473] {processor.py:163} INFO - Started process (PID=18337) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:58:09,475] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:58:09,475] {logging_mixin.py:109} INFO - [2021-10-29 07:58:09,475] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:58:09,483] {logging_mixin.py:109} INFO - [2021-10-29 07:58:09,482] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:58:09,497] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:58:09,507] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.037 seconds
[2021-10-29 07:58:39,847] {processor.py:163} INFO - Started process (PID=18371) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:58:39,859] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:58:39,860] {logging_mixin.py:109} INFO - [2021-10-29 07:58:39,860] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:58:39,868] {logging_mixin.py:109} INFO - [2021-10-29 07:58:39,867] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:58:39,923] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:58:39,995] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.162 seconds
[2021-10-29 07:59:10,549] {processor.py:163} INFO - Started process (PID=18395) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:59:10,551] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:59:10,551] {logging_mixin.py:109} INFO - [2021-10-29 07:59:10,551] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:59:10,559] {logging_mixin.py:109} INFO - [2021-10-29 07:59:10,558] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:59:10,575] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:59:10,588] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.042 seconds
[2021-10-29 07:59:41,090] {processor.py:163} INFO - Started process (PID=18428) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:59:41,137] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 07:59:41,139] {logging_mixin.py:109} INFO - [2021-10-29 07:59:41,139] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:59:41,163] {logging_mixin.py:109} INFO - [2021-10-29 07:59:41,162] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 07:59:41,222] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 07:59:41,250] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.164 seconds
[2021-10-29 08:00:11,794] {processor.py:163} INFO - Started process (PID=18453) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:00:11,811] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:00:11,811] {logging_mixin.py:109} INFO - [2021-10-29 08:00:11,811] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:00:11,820] {logging_mixin.py:109} INFO - [2021-10-29 08:00:11,819] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:00:11,840] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:00:11,858] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.068 seconds
[2021-10-29 08:00:42,380] {processor.py:163} INFO - Started process (PID=18477) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:00:42,383] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:00:42,384] {logging_mixin.py:109} INFO - [2021-10-29 08:00:42,384] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:00:42,393] {logging_mixin.py:109} INFO - [2021-10-29 08:00:42,392] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:00:42,408] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:00:42,417] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.041 seconds
[2021-10-29 08:01:12,755] {processor.py:163} INFO - Started process (PID=18501) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:01:12,757] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:01:12,758] {logging_mixin.py:109} INFO - [2021-10-29 08:01:12,758] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:01:12,766] {logging_mixin.py:109} INFO - [2021-10-29 08:01:12,765] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:01:12,781] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:01:12,790] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.038 seconds
[2021-10-29 08:01:43,423] {processor.py:163} INFO - Started process (PID=18525) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:01:43,427] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:01:43,428] {logging_mixin.py:109} INFO - [2021-10-29 08:01:43,427] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:01:43,436] {logging_mixin.py:109} INFO - [2021-10-29 08:01:43,435] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:01:43,452] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:01:43,465] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.046 seconds
[2021-10-29 08:02:13,849] {processor.py:163} INFO - Started process (PID=18549) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:02:13,850] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:02:13,851] {logging_mixin.py:109} INFO - [2021-10-29 08:02:13,851] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:02:13,861] {logging_mixin.py:109} INFO - [2021-10-29 08:02:13,860] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:02:13,885] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:02:13,901] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.055 seconds
[2021-10-29 08:02:44,324] {processor.py:163} INFO - Started process (PID=18573) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:02:44,327] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:02:44,329] {logging_mixin.py:109} INFO - [2021-10-29 08:02:44,328] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:02:44,338] {logging_mixin.py:109} INFO - [2021-10-29 08:02:44,337] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:02:44,398] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:02:44,405] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.085 seconds
[2021-10-29 08:03:14,906] {processor.py:163} INFO - Started process (PID=18607) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:03:14,911] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:03:14,922] {logging_mixin.py:109} INFO - [2021-10-29 08:03:14,922] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:03:14,930] {logging_mixin.py:109} INFO - [2021-10-29 08:03:14,929] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:03:14,951] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:03:14,975] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.072 seconds
[2021-10-29 08:03:45,352] {processor.py:163} INFO - Started process (PID=18631) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:03:45,363] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:03:45,364] {logging_mixin.py:109} INFO - [2021-10-29 08:03:45,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:03:45,371] {logging_mixin.py:109} INFO - [2021-10-29 08:03:45,370] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:03:45,420] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:03:45,431] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.083 seconds
[2021-10-29 08:04:15,896] {processor.py:163} INFO - Started process (PID=18662) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:04:15,912] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:04:15,913] {logging_mixin.py:109} INFO - [2021-10-29 08:04:15,913] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:04:15,921] {logging_mixin.py:109} INFO - [2021-10-29 08:04:15,920] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:04:15,992] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:04:16,028] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.135 seconds
[2021-10-29 08:04:46,265] {processor.py:163} INFO - Started process (PID=18689) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:04:46,271] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-29 08:04:46,271] {logging_mixin.py:109} INFO - [2021-10-29 08:04:46,271] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:04:46,299] {logging_mixin.py:109} INFO - [2021-10-29 08:04:46,299] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-29 08:04:46,359] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-29 08:04:46,412] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.155 seconds
