[2021-10-29 01:19:05,982] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A scheduled__2021-10-28T00:00:00+00:00 [queued]>
[2021-10-29 01:19:06,698] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A scheduled__2021-10-28T00:00:00+00:00 [queued]>
[2021-10-29 01:19:06,698] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-29 01:19:06,698] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-29 01:19:06,698] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-29 01:19:07,276] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): training_model_A> on 2021-10-28 00:00:00+00:00
[2021-10-29 01:19:07,592] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_A', 'scheduled__2021-10-28T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpkosfzu5p', '--error-file', '/tmp/tmpff6gk8hr']
[2021-10-29 01:19:07,639] {standard_task_runner.py:77} INFO - Job 26: Subtask training_model_A
[2021-10-29 01:19:07,402] {standard_task_runner.py:52} INFO - Started process 999 to run task
[2021-10-29 01:19:08,571] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.training_model_A scheduled__2021-10-28T00:00:00+00:00 [running]> on host 28ad64d5edf5
[2021-10-29 01:19:09,879] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-28T00:00:00+00:00
[2021-10-29 01:19:09,880] {python.py:152} INFO - Done. Returned value was: 1
[2021-10-29 01:19:10,109] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_A, execution_date=20211028T000000, start_date=20211029T011906, end_date=20211029T011910
[2021-10-29 01:19:10,337] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-29 01:19:10,843] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
