[2021-10-29 01:19:12,148] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_C scheduled__2021-10-28T00:00:00+00:00 [queued]>
[2021-10-29 01:19:12,334] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_C scheduled__2021-10-28T00:00:00+00:00 [queued]>
[2021-10-29 01:19:12,382] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-29 01:19:12,382] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-10-29 01:19:12,382] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-29 01:19:12,900] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): training_model_C> on 2021-10-28 00:00:00+00:00
[2021-10-29 01:19:12,945] {standard_task_runner.py:52} INFO - Started process 1002 to run task
[2021-10-29 01:19:13,008] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'training_model_C', 'scheduled__2021-10-28T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmputno9vx6', '--error-file', '/tmp/tmpefzny5s8']
[2021-10-29 01:19:13,008] {standard_task_runner.py:77} INFO - Job 28: Subtask training_model_C
[2021-10-29 01:19:13,448] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.training_model_C scheduled__2021-10-28T00:00:00+00:00 [running]> on host 28ad64d5edf5
[2021-10-29 01:19:13,935] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-10-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-28T00:00:00+00:00
[2021-10-29 01:19:13,972] {python.py:152} INFO - Done. Returned value was: 6
[2021-10-29 01:19:14,094] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_C, execution_date=20211028T000000, start_date=20211029T011912, end_date=20211029T011914
[2021-10-29 01:19:14,183] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-29 01:19:14,546] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
